// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKx9YiIwWCm0BXOYBrs9zqGp9goiXv76M',
    appId: '1:1050644401027:web:25ad5200f5112995b4c4b6',
    messagingSenderId: '1050644401027',
    projectId: 'lubase-c57c5',
    authDomain: 'lubase-c57c5.firebaseapp.com',
    storageBucket: 'lubase-c57c5.appspot.com',
    measurementId: 'G-2NN8Z7FR3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu-DFz9OSbvDtAgFP2BtNcn82SfC6lal0',
    appId: '1:1050644401027:android:47dd71fa5542b10ab4c4b6',
    messagingSenderId: '1050644401027',
    projectId: 'lubase-c57c5',
    storageBucket: 'lubase-c57c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg2uT1EJWVtsspEc9JP6mNbzwwGlgpx-g',
    appId: '1:1050644401027:ios:e3bc858c18f09f73b4c4b6',
    messagingSenderId: '1050644401027',
    projectId: 'lubase-c57c5',
    storageBucket: 'lubase-c57c5.appspot.com',
    iosClientId: '1050644401027-c3pev0nr2r3ngcmuil9d1sdretq48j1a.apps.googleusercontent.com',
    iosBundleId: 'com.example.name',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg2uT1EJWVtsspEc9JP6mNbzwwGlgpx-g',
    appId: '1:1050644401027:ios:e3bc858c18f09f73b4c4b6',
    messagingSenderId: '1050644401027',
    projectId: 'lubase-c57c5',
    storageBucket: 'lubase-c57c5.appspot.com',
    iosClientId: '1050644401027-c3pev0nr2r3ngcmuil9d1sdretq48j1a.apps.googleusercontent.com',
    iosBundleId: 'com.example.name',
  );
}
